"""
Pydantic schemas and data structures for THE 2047 judging engine.
Includes full Image Analysis Layer data models:
ReferenceProfile, ParticipantProfile, VisualEmbedding, ObjectFeature,
CompositionFeature, ColorFeature, LightingFeature, SceneFeature,
DetailFeature, StructureFeature, ComparisonResult, ScoringResult.
"""
from typing import List, Dict, Optional, Tuple, Any
from pydantic import BaseModel, Field
from app.models.enums import ImportanceLevel, SpatialQuadrant, AnalysisStatus, SceneType, ObjectMatchStatus


class BoundingBox(BaseModel):
    """Normalized bounding box coordinates (0.0 to 1.0)."""
    xmin: float = Field(0.0, ge=0.0, le=1.0)
    ymin: float = Field(0.0, ge=0.0, le=1.0)
    xmax: float = Field(1.0, ge=0.0, le=1.0)
    ymax: float = Field(1.0, ge=0.0, le=1.0)


class DominantColor(BaseModel):
    """Color representation with RGB, HEX and coverage percentage."""
    hex_code: str
    rgb: Tuple[int, int, int]
    percentage: float = Field(..., ge=0.0, le=100.0)
    color_name: Optional[str] = None


class VisualEmbedding(BaseModel):
    """Visual feature embedding generated by vision models."""
    model_name: str = "THE-2047-ViT-SpatialEmbedding"
    dimension: int = 512
    embedding: List[float] = Field(default_factory=list)
    is_normalized: bool = True


class ObjectFeature(BaseModel):
    """
    An identified visual object or element with location and 30-second memory importance.
    """
    name: str
    category: str = "general"
    importance: ImportanceLevel = ImportanceLevel.MEDIUM
    location: str = "center"  # e.g. "center-left", "upper-right", "lower-center"
    relative_size: float = Field(0.0, ge=0.0, le=100.0, description="Approximate area percentage")
    confidence: float = Field(1.0, ge=0.0, le=1.0)
    bounding_box: Optional[BoundingBox] = None
    quadrant: Optional[SpatialQuadrant] = None
    memory_prominence: str = "Salient visual subject"
    notes: Optional[str] = None
    match_status: Optional[ObjectMatchStatus] = None


# Backward-compatible alias
VisualElement = ObjectFeature


class SceneFeature(BaseModel):
    """Scene and environmental context."""
    scene_type: SceneType = SceneType.STUDIO_ABSTRACT
    location_type: str = "General environment"
    background: str = "Neutral background context"
    foreground: str = "Salient foreground visual subjects"
    general_environment: str = "Ambient scene environment"
    scene_context: str = "Visual scene composition"


class CompositionFeature(BaseModel):
    """
    Detailed composition and spatial arrangement features.
    """
    aspect_ratio: float = 1.0
    main_subject_position: str = "center"
    object_positions: Dict[str, str] = Field(
        default_factory=dict,
        description="Structured dictionary of object locations, e.g. {'main_subject': 'center-left'}"
    )
    foreground_background_relation: str = "Clear foreground subject separation"
    left_right_placement: str = "Centered horizontal balance"
    top_bottom_placement: str = "Even vertical distribution"
    relative_distances: List[str] = Field(default_factory=list)
    framing: str = "Medium shot framing"
    camera_viewpoint: str = "Eye-level perspective"
    spatial_relationships: Dict[str, str] = Field(default_factory=dict)
    quadrant_density: Dict[str, float] = Field(default_factory=dict)
    focal_center: Tuple[float, float] = (0.5, 0.5)
    symmetry_score: float = Field(0.5, ge=0.0, le=1.0)
    rule_of_thirds_adherence: float = Field(0.5, ge=0.0, le=1.0)
    layout_description: str = "Centered focal composition"


class ColorFeature(BaseModel):
    """
    Color palette, temperature, and chromatic relationships.
    """
    dominant_colors: List[DominantColor] = Field(default_factory=list)
    secondary_colors: List[DominantColor] = Field(default_factory=list)
    color_distribution: Dict[str, float] = Field(default_factory=dict)
    major_color_relationships: str = "Balanced tonal blend"
    average_brightness: float = Field(0.5, ge=0.0, le=1.0)
    contrast_ratio: float = Field(0.5, ge=0.0, le=1.0)
    warmth: float = Field(0.5, ge=0.0, le=1.0)
    saturation: float = Field(0.5, ge=0.0, le=1.0)
    lighting_description: Optional[str] = "Balanced medium-key lighting"


# Backward-compatible aliases
ColorProfile = ColorFeature
CompositionProfile = CompositionFeature


class LightingFeature(BaseModel):
    """
    Lighting and illumination characteristics.
    """
    brightness_key: str = "Balanced medium-key"
    lighting_direction: str = "Diffuse ambient illumination"
    time_of_day: str = "Neutral daytime appearance"
    contrast: float = Field(0.5, ge=0.0, le=1.0)
    shadow_prominence: str = "Moderate soft shadows"
    overall_mood: str = "Neutral clear atmosphere"
    lighting_description: str = "Balanced medium-key lighting"


class DetailFeature(BaseModel):
    """
    Important visual details reasonable for 30-second observation memory.
    """
    memorable_details: List[str] = Field(
        default_factory=list,
        description="Key memorable visual details perceptible within 30s observation"
    )
    prominent_motifs: List[str] = Field(default_factory=list)
    edge_density: float = Field(0.0, ge=0.0, le=1.0)
    texture_complexity: float = Field(0.0, ge=0.0, le=1.0)
    sharpness_score: float = Field(0.0, ge=0.0, le=1.0)


DetailProfile = DetailFeature


class StructureFeature(BaseModel):
    """Image physical dimensions and structural complexity."""
    aspect_ratio: float = 1.0
    width: int = 512
    height: int = 512
    main_regions: List[str] = Field(default_factory=list)
    visual_complexity: float = Field(0.5, ge=0.0, le=1.0)


# --- REFERENCE PROFILE ---

class ReferenceProfile(BaseModel):
    """
    Structured Reference Profile generated from the original competition image.
    This serves as the single source of truth for all participant evaluations.
    """
    image_id: str
    filename: str
    dimensions: Tuple[int, int]
    status: AnalysisStatus = AnalysisStatus.COMPLETED
    error_message: Optional[str] = None

    # A. Main Subject
    main_subject: Optional[ObjectFeature] = None

    # B. Secondary Subjects
    secondary_subjects: List[ObjectFeature] = Field(default_factory=list)

    # C. All Meaningful Objects
    objects: List[ObjectFeature] = Field(default_factory=list)

    # D. Scene / Environment
    scene: SceneFeature = Field(default_factory=SceneFeature)

    # E. Composition
    composition: CompositionFeature = Field(default_factory=CompositionFeature)

    # F. Colors
    colors: ColorFeature = Field(default_factory=ColorFeature)

    # G. Lighting
    lighting: LightingFeature = Field(default_factory=LightingFeature)

    # H. Visual Details
    details: DetailFeature = Field(default_factory=DetailFeature)

    # I. Image Structure
    structure: StructureFeature = Field(default_factory=StructureFeature)

    # Visual Embedding (CLIP)
    visual_embedding: Optional[VisualEmbedding] = None

    # Semantic Summary
    semantic_summary: str = ""

    # Detected Semantic Features
    detected_features: Dict[str, float] = Field(default_factory=dict)

    # Compatibility properties for existing engine consumers
    @property
    def main_subjects(self) -> List[ObjectFeature]:
        return [self.main_subject] if self.main_subject else []

    @property
    def dominant_colors(self) -> ColorFeature:
        return self.colors

    @property
    def visual_details(self) -> DetailFeature:
        return self.details

    @property
    def scene_environment(self) -> str:
        return self.scene.scene_context

    @property
    def background(self) -> str:
        return self.scene.background

    @property
    def foreground(self) -> str:
        return self.scene.foreground

    @property
    def spatial_relationships(self) -> List[str]:
        return [f"{k}: {v}" for k, v in self.composition.spatial_relationships.items()]


# --- PARTICIPANT PROFILE ---

class ParticipantProfile(BaseModel):
    """
    Structured profile of a participant's recreation.
    Generated independently using the exact same feature pipeline as ReferenceProfile.
    """
    participant_id: str
    filename: str
    dimensions: Tuple[int, int]
    status: AnalysisStatus = AnalysisStatus.COMPLETED
    error_message: Optional[str] = None

    # A. Main Subject
    main_subject: Optional[ObjectFeature] = None

    # B. Secondary Subjects
    secondary_subjects: List[ObjectFeature] = Field(default_factory=list)

    # C. Objects
    objects: List[ObjectFeature] = Field(default_factory=list)

    # D. Scene
    scene: Optional[SceneFeature] = None

    # E. Composition
    composition: Optional[CompositionFeature] = None

    # F. Colors
    colors: Optional[ColorFeature] = None

    # G. Lighting
    lighting: Optional[LightingFeature] = None

    # H. Visual Details
    details: Optional[DetailFeature] = None

    # I. Image Structure
    structure: Optional[StructureFeature] = None

    # Visual Embedding (CLIP)
    visual_embedding: Optional[VisualEmbedding] = None

    # Semantic Summary
    semantic_summary: str = ""

    # Detected Semantic Features
    detected_features: Dict[str, float] = Field(default_factory=dict)

    # Compatibility properties
    @property
    def detected_elements(self) -> List[ObjectFeature]:
        return self.objects

    @property
    def color_profile(self) -> Optional[ColorFeature]:
        return self.colors

    @property
    def composition_profile(self) -> Optional[CompositionFeature]:
        return self.composition

    @property
    def detail_profile(self) -> Optional[DetailFeature]:
        return self.details

    @property
    def dominant_colors(self) -> Optional[ColorFeature]:
        return self.colors

    @property
    def visual_details(self) -> Optional[DetailFeature]:
        return self.details


# --- COMPARISON & SCORING RESULTS (RESERVED FOR NEXT STAGE) ---

class ComparisonResult(BaseModel):
    """Comparison metrics between a participant and the reference."""
    participant_id: str
    semantic_similarity: float = 0.0
    object_accuracy: float = 0.0
    composition_similarity: float = 0.0
    color_similarity: float = 0.0
    detail_similarity: float = 0.0
    notes: Optional[str] = None


class CategoryScores(BaseModel):
    """Official points breakdown summing to 100 max."""
    semantic_similarity: float = Field(..., ge=0.0, le=30.0, description="Max 30.0")
    object_accuracy: float = Field(..., ge=0.0, le=25.0, description="Max 25.0")
    composition_spatial: float = Field(..., ge=0.0, le=20.0, description="Max 20.0")
    color_lighting: float = Field(..., ge=0.0, le=15.0, description="Max 15.0")
    fine_details: float = Field(..., ge=0.0, le=10.0, description="Max 10.0")
    total_score: float = Field(..., ge=0.0, le=100.0, description="Max 100.0")


class ScoringResult(BaseModel):
    """Official scoring result for a participant."""
    participant_id: str
    scores: CategoryScores
    final_score: float = 0.0
    rank: Optional[int] = None
    explanation: Optional[str] = None


class KeyElementAnalysis(BaseModel):
    """Analysis of a key reference element and its reproduction in participant image."""
    name: str
    importance: ImportanceLevel = ImportanceLevel.MEDIUM
    status: ObjectMatchStatus = ObjectMatchStatus.PRESENT
    notes: Optional[str] = None
    icon: str = "✓"  # "✓" for matched, "△" for partial, "✗" for missing


class ComparisonSummary(BaseModel):
    """Concise structured breakdown of what was reproduced, missing, and different."""
    reproduced_correctly: List[str] = Field(default_factory=list)
    partially_reproduced: List[str] = Field(default_factory=list)
    missing: List[str] = Field(default_factory=list)
    composition_differences: List[str] = Field(default_factory=list)
    color_lighting_differences: List[str] = Field(default_factory=list)
    detail_differences: List[str] = Field(default_factory=list)


class JudgingReport(BaseModel):
    """
    Comprehensive structured judging report produced by the Explanation Engine.
    Exclusively grounded in actual comparison evidence and numerical scores.
    """
    participant_id: str
    final_score: float
    score_tier: str  # "Exceptional match", "Very strong match", "Strong match", "Moderate match", "Partial match", "Weak match", "Very low match"
    overall_explanation: str
    category_explanations: Dict[str, str] = Field(default_factory=dict)
    strengths: List[str] = Field(default_factory=list)  # List of "✓ ..."
    differences: List[str] = Field(default_factory=list)  # List of "△ ..." and "✗ ..."
    strongest_areas: List[str] = Field(default_factory=list)  # Categories ranked by % of max points
    areas_to_improve: List[str] = Field(default_factory=list)  # Categories with lowest % of max points
    key_elements: List[KeyElementAnalysis] = Field(default_factory=list)
    comparison_summary: ComparisonSummary = Field(default_factory=ComparisonSummary)


class StructuredEvidence(BaseModel):
    """
    Structured deterministic comparison evidence for a participant recreation.
    Feeds the detailed dossier UI and explanation system.
    """
    participant_id: str
    final_score: float = 0.0
    semantic_score: float = 0.0
    object_score: float = 0.0
    composition_score: float = 0.0
    color_lighting_score: float = 0.0
    detail_score: float = 0.0
    matched_elements: List[str] = Field(default_factory=list)
    partially_matched_elements: List[str] = Field(default_factory=list)
    missing_elements: List[str] = Field(default_factory=list)
    unexpected_elements: List[str] = Field(default_factory=list)
    composition_differences: List[str] = Field(default_factory=list)
    color_differences: List[str] = Field(default_factory=list)
    detail_differences: List[str] = Field(default_factory=list)
    strengths: List[str] = Field(default_factory=list)


class FeatureComparisonMetrics(BaseModel):
    """Raw computed comparison metrics across all 5 dimensions."""
    semantic_similarity_raw: float = Field(0.0, ge=0.0, le=1.0)
    high_importance_found_ratio: float = Field(0.0, ge=0.0, le=1.0)
    medium_importance_found_ratio: float = Field(0.0, ge=0.0, le=1.0)
    low_importance_found_ratio: float = Field(0.0, ge=0.0, le=1.0)
    weighted_object_score_raw: float = Field(0.0, ge=0.0, le=1.0)
    matched_elements: List[str] = Field(default_factory=list)
    partially_matched_elements: List[str] = Field(default_factory=list)
    missed_elements: List[str] = Field(default_factory=list)
    extraneous_elements: List[str] = Field(default_factory=list)
    composition_differences: List[str] = Field(default_factory=list)
    color_differences: List[str] = Field(default_factory=list)
    detail_differences: List[str] = Field(default_factory=list)
    strengths: List[str] = Field(default_factory=list)
    focal_distance: float = Field(0.0, ge=0.0, le=1.0)
    quadrant_correlation: float = Field(0.0, ge=-1.0, le=1.0)
    symmetry_match: float = Field(0.0, ge=0.0, le=1.0)
    composition_score_raw: float = Field(0.0, ge=0.0, le=1.0)
    color_palette_similarity: float = Field(0.0, ge=0.0, le=1.0)
    brightness_similarity: float = Field(0.0, ge=0.0, le=1.0)
    warmth_similarity: float = Field(0.0, ge=0.0, le=1.0)
    contrast_similarity: float = Field(0.0, ge=0.0, le=1.0)
    saturation_similarity: float = Field(0.0, ge=0.0, le=1.0)
    color_lighting_score_raw: float = Field(0.0, ge=0.0, le=1.0)
    edge_density_similarity: float = Field(0.0, ge=0.0, le=1.0)
    texture_similarity: float = Field(0.0, ge=0.0, le=1.0)
    sharpness_similarity: float = Field(0.0, ge=0.0, le=1.0)
    fine_detail_score_raw: float = Field(0.0, ge=0.0, le=1.0)


class HumanEvaluation(BaseModel):
    """Human judge manual evaluation for calibration."""
    participant_id: str
    human_score: float = Field(..., ge=0.0, le=100.0)
    human_semantic: Optional[float] = Field(None, ge=0.0, le=30.0)
    human_object: Optional[float] = Field(None, ge=0.0, le=25.0)
    human_composition: Optional[float] = Field(None, ge=0.0, le=20.0)
    human_color: Optional[float] = Field(None, ge=0.0, le=15.0)
    human_detail: Optional[float] = Field(None, ge=0.0, le=10.0)
    human_comments: Optional[str] = None
    evaluator_name: Optional[str] = "Human Evaluator"
    submitted_at: Optional[str] = None


class HumanScoreOverride(BaseModel):
    """Non-destructive human score override with full audit trail."""
    participant_id: str
    original_ai_score: float
    override_score: float = Field(..., ge=0.0, le=100.0)
    override_reason: str
    organizer_name: str = "Lead Organizer"
    timestamp: str
    flagged_for_review: bool = True


class DisagreementItem(BaseModel):
    """Identified divergence between Human Score and AI Score."""
    participant_id: str
    human_score: float
    ai_score: float
    difference: float
    abs_difference: float
    is_significant: bool = False  # True if abs(difference) > 10.0
    main_category_disagreement: str = "Overall"
    category_differences: Dict[str, float] = Field(default_factory=dict)
    human_comments: Optional[str] = None


class CalibrationStats(BaseModel):
    """Statistical summary comparing Human evaluations with AI scoring."""
    total_samples: int
    human_avg_score: float
    ai_avg_score: float
    mean_absolute_error: float
    mean_difference: float  # bias (positive = human scored higher, negative = AI scored higher)
    pearson_correlation: float
    spearman_rank_correlation: float
    ranking_agreement_pct: float
    category_mae: Dict[str, float] = Field(default_factory=dict)
    significant_disagreements: List[DisagreementItem] = Field(default_factory=list)
    decision: str = "🟢 CALIBRATION ACCEPTABLE"
    decision_rationale: str = ""
    recommendations: List[str] = Field(default_factory=list)


class EvaluationResult(BaseModel):
    """Evaluation output for a single participant."""
    participant_id: str
    filename: str
    scores: CategoryScores
    explanation: str = ""
    category_reasons: Dict[str, str] = Field(default_factory=dict)
    comparison_metrics: Optional[FeatureComparisonMetrics] = None
    evidence: Optional[StructuredEvidence] = None
    judging_report: Optional[JudgingReport] = None
    is_duplicate: bool = False
    duplicate_of: Optional[str] = None
    image_hash: Optional[str] = None
    human_evaluation: Optional[HumanEvaluation] = None
    human_override: Optional[HumanScoreOverride] = None
    flagged_for_review: bool = False


class CalibrationAnalyzeRequest(BaseModel):
    """Request payload to compute calibration metrics against current evaluations."""
    human_evaluations: List[HumanEvaluation]
    evaluations: Optional[List[EvaluationResult]] = None


class ABConfigSimulationRequest(BaseModel):
    """Request payload to simulate alternative scoring category weights."""
    config_name: str = "Custom Configuration B"
    semantic_weight: float = Field(30.0, ge=0.0, le=100.0)
    object_weight: float = Field(25.0, ge=0.0, le=100.0)
    composition_weight: float = Field(20.0, ge=0.0, le=100.0)
    color_weight: float = Field(15.0, ge=0.0, le=100.0)
    detail_weight: float = Field(10.0, ge=0.0, le=100.0)
    human_evaluations: List[HumanEvaluation]


class ABConfigSimulationResponse(BaseModel):
    """Comparative response evaluating Current Config vs Proposed Config."""
    config_a_name: str = "Default (30/25/20/15/10)"
    config_a_mae: float
    config_a_correlation: float
    config_a_ranking_agreement_pct: float
    config_b_name: str
    config_b_weights: Dict[str, float]
    config_b_mae: float
    config_b_correlation: float
    config_b_ranking_agreement_pct: float
    mae_improvement: float  # positive means B is closer to human scores
    recommendation: str


class FlagForReviewRequest(BaseModel):
    """Request to flag or unflag a participant for human review."""
    participant_id: str
    flagged: bool = True
    reason: Optional[str] = None


class HumanOverrideRequest(BaseModel):
    """Request to record a non-destructive human score override."""
    participant_id: str
    override_score: float = Field(..., ge=0.0, le=100.0)
    override_reason: str
    organizer_name: Optional[str] = "Competition Organizer"


class RankedParticipant(BaseModel):
    """Leaderboard entry for a ranked participant."""
    rank: int
    participant_id: str
    filename: str
    total_score: float
    scores: CategoryScores
    explanation: str = ""
    tier: str = "Contender"
    percentile: float = 0.0
    is_tied: bool = False
    is_duplicate: bool = False
    duplicate_of: Optional[str] = None
    image_hash: Optional[str] = None
    evidence: Optional[StructuredEvidence] = None
    judging_report: Optional[JudgingReport] = None
    human_evaluation: Optional[HumanEvaluation] = None
    human_override: Optional[HumanScoreOverride] = None
    flagged_for_review: bool = False


class AuditMetadata(BaseModel):
    """Audit and reproducibility metadata for competition results verification."""
    engine_version: str = "THE-2047-PROD-v1.0"
    timestamp: str
    total_evaluated: int
    category_weights: Dict[str, float]
    execution_duration_sec: float
    scoring_hash: Optional[str] = None
    reference_hash: Optional[str] = None
    participant_hashes: Dict[str, str] = Field(default_factory=dict)
    duplicate_flags: Dict[str, str] = Field(default_factory=dict)
    analyzer_versions: Dict[str, str] = Field(default_factory=dict)
    consistency_checks_passed: bool = True
    consistency_issues_count: int = 0
    human_overrides_count: int = 0
    flagged_for_review_count: int = 0


class CalibrationInspectResponse(BaseModel):
    """Deep diagnostic inspection payload for developer calibration mode."""
    reference_id: str
    participant_id: str
    scores: CategoryScores
    comparison_metrics: FeatureComparisonMetrics
    reference_objects: List[ObjectFeature] = Field(default_factory=list)
    participant_objects: List[ObjectFeature] = Field(default_factory=list)
    quadrant_density_reference: Dict[str, float] = Field(default_factory=dict)
    quadrant_density_participant: Dict[str, float] = Field(default_factory=dict)
    dominant_colors_reference: List[DominantColor] = Field(default_factory=list)
    dominant_colors_participant: List[DominantColor] = Field(default_factory=list)
    consistency_passed: bool = True
    consistency_warnings: List[str] = Field(default_factory=list)
    judging_report: Optional[JudgingReport] = None


class ParticipantStatusInfo(BaseModel):
    """Participant status tracking for live dashboard and session resumption."""
    participant_id: str
    filename: str
    original_filename: Optional[str] = None
    file_url: Optional[str] = None
    status: str = "PENDING"  # "PENDING", "PROCESSING", "COMPLETED", "FAILED"
    error: Optional[str] = None
    last_evaluated_at: Optional[str] = None
    flagged_for_review: bool = False


class JudgingSession(BaseModel):
    """Complete judging session state for persistence and resumption."""
    session_id: str
    session_name: str = "Live Competition Session"
    created_at: str
    updated_at: str
    status: str = "READY"  # "READY", "PROCESSING", "COMPLETED"
    reference_filename: Optional[str] = None
    reference_profile: Optional[ReferenceProfile] = None
    participants: List[ParticipantStatusInfo] = Field(default_factory=list)
    evaluation_results: List[EvaluationResult] = Field(default_factory=list)
    ranked_results: List[RankedParticipant] = Field(default_factory=list)
    audit_metadata: Optional[AuditMetadata] = None
    human_evaluations: List[HumanEvaluation] = Field(default_factory=list)
    human_overrides: List[HumanScoreOverride] = Field(default_factory=list)
    calibration_stats: Optional[CalibrationStats] = None


class BatchEvaluationResponse(BaseModel):
    """Response payload for competition evaluation."""
    reference_id: str
    reference_profile: ReferenceProfile
    total_participants: int
    ranked_results: List[RankedParticipant]
    processing_time_seconds: float
    audit_metadata: Optional[AuditMetadata] = None
    calibration_stats: Optional[CalibrationStats] = None


class BatchAnalysisResponse(BaseModel):
    """
    Response payload for the Image Analysis Layer.
    Contains independent profiles for reference and all up to 60 participants.
    """
    reference_id: str
    reference_profile: ReferenceProfile
    total_participants: int
    completed_count: int
    failed_count: int
    participant_profiles: List[ParticipantProfile]
    processing_time_seconds: float


class ValidationResponse(BaseModel):
    """Validation result for uploaded images."""
    valid: bool
    filename: str
    error: Optional[str] = None
    dimensions: Optional[Tuple[int, int]] = None
    file_size_bytes: Optional[int] = None
    mime_type: Optional[str] = None
